spring.application.name=User-Management-With-Security

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/UserManagement
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
#logging.level.org.springframework.security=DEBUG

###########jwt##########
app.jwt.secret=
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000